title: 'Tecnología 4º ESO'
subtitle: 'Apuntes de Sergio Rodríguez'
theme: jekyll-theme-midnight
light: true
description: 'Apuntes de la asignatura de Tecnología de 4º ESO'
acronym: AAT
exclude: [ '_drafts/2021/', '_drafts/2020' ]
baseurl: '/asignatura-website-sergio-rodriguez-0100699968/' # '/introduccion'
#url: https://ull-mfp-aet-2223.github.io/ull-mfp-aet-2223.github.io
guia_docente: 
show_downloads: false
calendario_academico: 
horarios_examenes: 
calendario_examenes:
horarios_tutorias:
organization: 
  url: https://github.com/ULL-MFP-AET-2324-alu0100699968
  name: ULL-MFP-AET-2324-alu0100699968
  master: https://github.dev/ULL-MFP-AET/ull-mfp-aet.github.io/blob/main/
profesor: 
profesor_github: alu0100699968
chat: https://chat.google.com
future: true
disqus: 
  url: https://procesadores-de-lenguajes.disqus.com/embed.js
  comments: true
classroom: 
  url: "https://classroom.github.com/classrooms/149103359-ull-mfp-aet-2324-alu0100699968"
  name: ULL-MFP-AET-2324-alu0100699968
collections:
  tareas:
    output: true
temas:
# - title: 'Introducción al Desarrollo Colaborativo de Proyectos en la Nube'
#    url: '/tema0-introduccion/'
#    hover: 'introduccion'
# - title: 'Desarrollo Colaborativo de Proyectos en la Nube con GitHub Education'
#  url: '/tema1-github-education'
#  hover: 'github-education'
# - title: 'Desarrollo Colaborativo de Proyectos en la Nube con Google'
#  url: /tema2-google-app-scripts
#  hover: 'google-app-scripts' 
plugins:
  - jemoji

